// Purpose: Parse feeds, version artifacts, gate texts, bound candidates and deliver reliable digests.
import{createHash}from'node:crypto';import{writeFile,mkdir}from'node:fs/promises';import{dirname}from'node:path';const hash=x=>createHash('sha256').update(x).digest('hex'),strip=x=>x.replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]+>/g,'').trim(),tags=(block,name)=>[...block.matchAll(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,'gi'))].map(x=>strip(x[1]));
export function parseFeed(xml){const atom=/<feed[\s>]/i.test(xml),blocks=[...xml.matchAll(atom?/<entry[\s>][\s\S]*?<\/entry>/gi:/<item[\s>][\s\S]*?<\/item>/gi)].map(x=>x[0]);return blocks.map((b,i)=>({id:tags(b,atom?'id':'guid')[0]??tags(b,'link')[0]??`entry-${i}`,title:tags(b,'title')[0]??'',text:tags(b,atom?'content':'description')[0]??'',url:atom?(b.match(/<link[^>]+href=["']([^"']+)/i)?.[1]??''):(tags(b,'link')[0]??'')})).filter(x=>x.title||x.text)}
export function register(store,artifact){const contentHash=hash(artifact.text),versions=store.get(artifact.id)??[];if(!versions.some(x=>x.contentHash===contentHash))versions.push({...artifact,contentHash,version:versions.length+1});store.set(artifact.id,versions);return versions.at(-1)}
export function passes(text,source,state,{dateFrom,dateTo,allowSources=[]}={}){const contentHash=hash(text.text);if(state.seen?.has(contentHash))return{ok:false,reason:'seen',contentHash};if(text.jurisdiction&&!source.jurisdictions?.includes(text.jurisdiction))return{ok:false,reason:'jurisdiction',contentHash};if(allowSources.length&&!allowSources.includes(source.id))return{ok:false,reason:'source',contentHash};if(dateFrom&&text.date<dateFrom||dateTo&&text.date>dateTo)return{ok:false,reason:'date',contentHash};return{ok:true,contentHash}}
const tok=x=>new Set(x.toLowerCase().match(/[a-z0-9]+/g)??[]);export function candidates(text,artifacts,limit=10){return artifacts.filter(a=>!text.jurisdiction||a.jurisdictions?.includes(text.jurisdiction)).map(a=>({a,score:[...tok(text.text)].filter(x=>tok(a.text).has(x)).length})).sort((x,y)=>y.score-x.score||x.a.id.localeCompare(y.a.id)).slice(0,limit).map(x=>x.a)}
export function mandatory(text,source,config){const hay=`${text.title} ${text.text}`.toLowerCase();return(config.categories??[]).includes(text.category)||(config.sources??[]).includes(source.id)||(config.keywords??[]).find(x=>hay.includes(x.toLowerCase()))}
export async function evaluate(text,source,artifacts,provider,config={}){const wake=mandatory(text,source,config.mandatory??{});if(wake)return{mandatory:true,alerts:artifacts.map(a=>({artifactId:a.id,owner:a.owner,probability:1,reason:'mandatory wake-up'}))};const chosen=candidates(text,artifacts,config.limit??10),answers=await provider.judge(text,chosen);return{mandatory:false,alerts:chosen.map((a,i)=>({artifactId:a.id,owner:a.owner,probability:answers[i]})).filter(x=>x.probability>=(config.threshold??.5))}}
export function reconcile(fetched,evaluated){const done=new Set(evaluated.map(x=>x.contentHash));return fetched.filter(x=>!done.has(hash(x.text))).map(x=>x.id)}
export async function writeDigest(path,reports){await mkdir(dirname(path),{recursive:true});await writeFile(path,JSON.stringify({generatedAt:new Date().toISOString(),reports},null,2))}
export async function webhook(url,payload,{fetchImpl=fetch,timeoutMs=5000}={}){try{const r=await fetchImpl(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(timeoutMs),redirect:'error'});if(!r.ok)throw Error(`HTTP ${r.status}`);return{ok:true}}catch(e){return{ok:false,error:e.message}}}
export function wilson(k,n){const z=1.959963984540054,p=k/n,d=1+z*z/n,c=(p+z*z/(2*n))/d,h=z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/d;return[Math.max(0,c-h),Math.min(1,c+h)]}export function measure(rows,threshold=.5){const impacts=rows.filter(x=>x.label),misses=impacts.filter(x=>x.probability<threshold).length;return{impacts:impacts.length,falseNegatives:misses,falseNegativeRate:misses/impacts.length,interval:wilson(misses,impacts.length)}}
export class FakeJev{constructor(values=[]){this.values=values;this.calls=[]}async judge(text,artifacts){this.calls.push({text,artifacts});return artifacts.map((_,i)=>this.values[i]??0)}}
